### ISSUE TITLE
VIRL doesn't start.

### ISSUE THREAD

**Issue by reca** [Snergster/virl_packet#4]
Fresh deploy with current GIT version, no success:

# git log | head
commit 9327b80ae00e27a18ef32fcdd7f40abf1bee1d4d
Author: Ed Kern <ejkern@mac.com>
Date:   Fri Nov 11 09:41:03 2016 -0700

    overcommit numbers bumped to 5 and 10

but:

root@virltest:~# virl_health_status 
Traceback (most recent call last):
  File "/home/jenkins/jenkins/jobs/VIRL_CORE_build/workspace/test-virl-repo/bin/virl_health_status", line 20, in <module>
  File "/home/jenkins/jenkins/jobs/VIRL_CORE_build/workspace/test-virl-repo/virl/health/__init__.py", line 7, in health
  File "/home/jenkins/jenkins/jobs/VIRL_CORE_build/workspace/test-virl-repo/virl/server/model.py", line 25, in model
  File "/home/jenkins/jenkins/jobs/VIRL_CORE_build/workspace/test-virl-repo/virl/std/client.py", line 1250, in client
  File "/home/jenkins/jenkins/jobs/VIRL_CORE_build/workspace/test-virl-repo/virl/std/client.py", line 1262, in WebSocketClient
AttributeError: 'module' object has no attribute 'ABNF'

Any ideas?

**Comment by Snergster** [comment]
git it another try...there were issues with the newly released salt 2016.11 that broke the way we extracted a tar file or two.  should be ok now...sorry for the trouble
